const RasaMessagePrefix = {
    CLIENT_PUT_CONTACTS_QUERY: "CLIENT_PUT_CONTACTS_QUERY",
    CLIENT_PUT_INTRA_QUERY: "CLIENT_PUT_INTRA_QUERY",
    CLIENT_SAVE_INTRA: "CLIENT_SAVE_INTRA"
}

export default RasaMessagePrefix;